[2025-03-06T05:41:55.817+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-06T05:41:55.842+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlbooksdb_flipkart.insert_book_data manual__2025-03-06T05:25:15.334856+00:00 [queued]>
[2025-03-06T05:41:55.851+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlbooksdb_flipkart.insert_book_data manual__2025-03-06T05:25:15.334856+00:00 [queued]>
[2025-03-06T05:41:55.852+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-06T05:41:55.865+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): insert_book_data> on 2025-03-06 05:25:15.334856+00:00
[2025-03-06T05:41:55.876+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mlbooksdb_flipkart', 'insert_book_data', 'manual__2025-03-06T05:25:15.334856+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/buildmlbooksdb.py', '--cfg-path', '/tmp/tmp_wd7rsxj']
[2025-03-06T05:41:55.874+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=345) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-06T05:41:55.878+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask insert_book_data
[2025-03-06T05:41:55.878+0000] {standard_task_runner.py:72} INFO - Started process 350 to run task
[2025-03-06T05:41:55.921+0000] {task_command.py:467} INFO - Running <TaskInstance: mlbooksdb_flipkart.insert_book_data manual__2025-03-06T05:25:15.334856+00:00 [running]> on host 3f07eaa845dd
[2025-03-06T05:41:55.973+0000] {logging_mixin.py:190} INFO - No data to insert.
[2025-03-06T05:41:55.997+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mlbooksdb_flipkart' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T05:25:15.334856+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-06T05:25:15.334856+00:00'
[2025-03-06T05:41:55.998+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-06T05:41:55.999+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-06T05:41:56.000+0000] {logging_mixin.py:190} INFO - Current task name:insert_book_data state:running start_date:2025-03-06 05:41:55.843391+00:00
[2025-03-06T05:41:56.000+0000] {logging_mixin.py:190} INFO - Dag name:mlbooksdb_flipkart and current dag run status:running
[2025-03-06T05:41:56.001+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-06T05:41:56.002+0000] {sql.py:295} INFO - Executing: None
[2025-03-06T05:41:56.012+0000] {base.py:84} INFO - Retrieving connection 'mlbooks_collection'
[2025-03-06T05:41:56.016+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 461, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2025-03-06T05:41:56.028+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-06T05:41:56.029+0000] {logging_mixin.py:190} INFO - Task start:2025-03-06 05:41:55.843391+00:00 end:2025-03-06 05:41:56.028354+00:00 duration:0.184963
[2025-03-06T05:41:56.030+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): insert_book_data> dag:<DAG: mlbooksdb_flipkart> dagrun:<DagRun mlbooksdb_flipkart @ 2025-03-06 05:25:15.334856+00:00: manual__2025-03-06T05:25:15.334856+00:00, state:running, queued_at: 2025-03-06 05:25:15.371350+00:00. externally triggered: True>
[2025-03-06T05:41:56.031+0000] {logging_mixin.py:190} INFO - Failure caused by List of SQL statements is empty
[2025-03-06T05:41:56.031+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=mlbooksdb_flipkart, task_id=insert_book_data, run_id=manual__2025-03-06T05:25:15.334856+00:00, execution_date=20250306T052515, start_date=20250306T054155, end_date=20250306T054156
[2025-03-06T05:41:56.060+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-06T05:41:56.061+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task insert_book_data (List of SQL statements is empty; 350)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 461, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2025-03-06T05:41:56.094+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-06T05:41:56.111+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-06T05:41:56.114+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
