[2025-03-06T06:08:19.740+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-06T06:08:19.784+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlbooksdb_flipkart.insert_book_data manual__2025-03-06T06:08:04.475799+00:00 [queued]>
[2025-03-06T06:08:19.804+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlbooksdb_flipkart.insert_book_data manual__2025-03-06T06:08:04.475799+00:00 [queued]>
[2025-03-06T06:08:19.805+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-06T06:08:19.831+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): insert_book_data> on 2025-03-06 06:08:04.475799+00:00
[2025-03-06T06:08:19.847+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=719) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-06T06:08:19.849+0000] {standard_task_runner.py:72} INFO - Started process 721 to run task
[2025-03-06T06:08:19.849+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mlbooksdb_flipkart', 'insert_book_data', 'manual__2025-03-06T06:08:04.475799+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/buildmlbooksdb.py', '--cfg-path', '/tmp/tmphuqrzutr']
[2025-03-06T06:08:19.851+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask insert_book_data
[2025-03-06T06:08:19.918+0000] {task_command.py:467} INFO - Running <TaskInstance: mlbooksdb_flipkart.insert_book_data manual__2025-03-06T06:08:04.475799+00:00 [running]> on host 3f07eaa845dd
[2025-03-06T06:08:20.012+0000] {logging_mixin.py:190} INFO - Error generating SQL statements: 'title'
[2025-03-06T06:08:20.013+0000] {logging_mixin.py:190} INFO - Generated 0 SQL statements.
[2025-03-06T06:08:20.053+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mlbooksdb_flipkart' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T06:08:04.475799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-06T06:08:04.475799+00:00'
[2025-03-06T06:08:20.055+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-06T06:08:20.056+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-06T06:08:20.058+0000] {logging_mixin.py:190} INFO - Current task name:insert_book_data state:running start_date:2025-03-06 06:08:19.786050+00:00
[2025-03-06T06:08:20.059+0000] {logging_mixin.py:190} INFO - Dag name:mlbooksdb_flipkart and current dag run status:running
[2025-03-06T06:08:20.060+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-06T06:08:20.061+0000] {sql.py:295} INFO - Executing: []
[2025-03-06T06:08:20.073+0000] {base.py:84} INFO - Retrieving connection 'mlbooks_collection'
[2025-03-06T06:08:20.079+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 461, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2025-03-06T06:08:20.099+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-06T06:08:20.100+0000] {logging_mixin.py:190} INFO - Task start:2025-03-06 06:08:19.786050+00:00 end:2025-03-06 06:08:20.099047+00:00 duration:0.312997
[2025-03-06T06:08:20.101+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): insert_book_data> dag:<DAG: mlbooksdb_flipkart> dagrun:<DagRun mlbooksdb_flipkart @ 2025-03-06 06:08:04.475799+00:00: manual__2025-03-06T06:08:04.475799+00:00, state:running, queued_at: 2025-03-06 06:08:04.761797+00:00. externally triggered: True>
[2025-03-06T06:08:20.102+0000] {logging_mixin.py:190} INFO - Failure caused by List of SQL statements is empty
[2025-03-06T06:08:20.103+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=mlbooksdb_flipkart, task_id=insert_book_data, run_id=manual__2025-03-06T06:08:04.475799+00:00, execution_date=20250306T060804, start_date=20250306T060819, end_date=20250306T060820
[2025-03-06T06:08:20.146+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-06T06:08:20.147+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task insert_book_data (List of SQL statements is empty; 721)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 461, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2025-03-06T06:08:20.187+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-06T06:08:20.217+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-06T06:08:20.220+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
